
<?php
// print_r($this->cache);
// die; 
      $this->cache->set('Setting',$this->translator->_('Setting'));
      $this->cache->set('Add_Product',$this->translator->_('Add_Product'));
      $this->cache->set('Add_Role',$this->translator->_('Add_Role'));
      $this->cache->set('Action',$this->translator->_('Action'));
      $this->cache->set('Product_List',$this->translator->_('Product_List'));
    //   // die; 
    // echo $this->cache->get('Setting'); 
    // die;
      
?>
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title></title>
  <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css'>
<link rel="stylesheet" href="/home/cedcoss/git /events_phalcon/src/app/views/index/style.css">

</head>
<body>
<!-- partial:index.partial.html -->
<!-- <section class="card mt-5 mb-5"> -->
<!-- Example single danger button -->
<div class="container mb-4 mt-4">
<div class="mt-5 text-center"><h3></h3></div>

<h2>change your Language</h2>

    <?php echo $this->tag->form(['','method'=>'get']); ?>
        <p>
        <?php 
            if(isset($message)){ 
                echo $message;
            } 
        ?>

    </p>

        <p>
            <label for="name">Change Language</label>
            <?php echo $this->tag->select([
                'option',
                [
                  'en_US'=>'en_US',
                  'locale'=>'locale'
                ],
                'class'=>"form-control",
                'onchange'=>"this.form.submit()",
                "name"=>'locale'

                ]); ?>
        </p>


</div>
<!-- </section> -->
<nav class="navbar navbar-expand-lg navbar-light bg-primary p-5">
  <a class="navbar-brand" href="#"><?php echo $this->translator->_('Navbar') ?></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav p-5 mr-auto">
      <!-- <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li> -->
      <li class="nav-item card p-3 m-3">
        <a class="nav-link" href="order"><?php 
        if($this->cache->has('checkout')){
          echo $this->cache->get('Checkout');

        }else{
        echo $this->translator->_('Checkout'); }?>
        </a>
    
      </li>
      <li class="nav-item card p-3 m-3">
        <a class="nav-link" href="/setting"><?php 
        if( $this->cache->has('Setting')){
          echo $this->cache->get('Setting');
        }
        // echo $this->translator->_('Setting')
         ?>
        </a>
      </li>
      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">checkout</a>
          <a class="dropdown-item" href="#"></a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> -->
      <li class="nav-item card p-3 m-3">
        <a class="nav-link " href="addpro">
        <?php 
        if( $this->cache->has('Add_Product')){
          echo $this->cache->get('Add_Product');
        }
       ?>
       </a>
      </li>
      <li class="nav-item card p-3 m-3">
      <a class="nav-link" href="/role"><?php 
        if( $this->cache->has('Add_Role')){
          echo $this->cache->get('Add_Role');
        }
        // echo $this->translator->_('Setting')
         ?>
        </a>
      </li>
      <li class="nav-item card p-3 m-3">
   
      <a class="nav-link" href="role/action"><?php 
        if( $this->cache->has('Action')){
          echo $this->cache->get('Action');
        }
        // echo $this->translator->_('Setting')
         ?>
        </a>/a>
      </li>
      <li class="nav-item card p-3 m-3">
      
        <a class="nav-link " href="index/list"><?php echo $this->translator->_('Product_List') ?></a>
      </li>
    </ul>
   </div>
</nav>

<!-- partial -->
  
</body>
</html>
